version: '3.9'
services:
  database:
    container_name: employee-skills-db
    image: 'postgres:15.1'
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - ~/docker-data/employee-skills-db:/var/lib/postgresql/data
      - ./postgres/skills-matrix-schema.sql:/docker-entrypoint-initdb.d/skills-matrix-schema.sql
  
  service:
    container_name: employee-skills-service
    build:
      context: ./employee-skills-service
    restart: always
    ports:
      - 8080:8080
    links:
      - database
  
  ui:
    container_name: employee-skills-ui
    build:
      context: ./employee-skills-ui
    restart: always
    ports:
      - 80:80
    links:
      - service

  