version: '3.9'
services:
  database:
    container_name: employee-skills-db
    image: 'postgres:15.1'
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - ~/docker-data/employee-skills-db:/var/lib/postgresql/data
  
  service:
    container_name: employee-skills-service
    build:
      context: ./employee-skills-service
      dockerfile: .devcontainer/Dockerfile
    ports:
      - 8080:8080
    command: /bin/sh -c "while sleep 1000; do :; done"
    links:
      - database
  
  ui:
    container_name: employee-skills-ui
    build:
      context: ./employee-skills-ui
      dockerfile: .devcontainer/Dockerfile
    command: /bin/sh -c "while sleep 1000; do :; done"
    links:
      - service

  