export const FETCH_EMPLOYEE_REQUEST = 'FETCH_EMPLOYEE_REQUEST';
export const FETCH_EMPLOYEE_SUCCESS = 'FETCH_EMPLOYEE_SUCCESS';
export const FETCH_EMPLOYEE_FAILURE = 'FETCH_EMPLOYEE_FAILURE';
export const SELECT_EMPLOYEE = 'SELECT_EMPLOYEE';
export const UPLOAD_EMPLOYEE_DATA = 'UPLOAD_EMPLOYEE_DATA';